# This file was generated by GoReleaser. DO NOT EDIT.
cask "hubbound" do
  name "hubbound"
  desc "Hubbound CLI, daemon, user agent, and privileged helper."
  homepage "https://hubbound.net"
  version "0.1.55-dev.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hubbound"
  binary "hubboundd"
  binary "hubbound-agent"
  binary "hubbound-helper"

  on_macos do
    on_intel do
      url "https://github.com/KodastrDevelopment/hubbound-releases/releases/download/v#{version}/hubbound_darwin_amd64.tar.gz"
      sha256 "e570ffd73d6e35e86dee673841e096b1df65b6e3a2d1b2f4e57ccf7b0582a84e"
    end
    on_arm do
      url "https://github.com/KodastrDevelopment/hubbound-releases/releases/download/v#{version}/hubbound_darwin_arm64.tar.gz"
      sha256 "dc63c3d51b50e0f5a2685240beb3092989911cdfe334283b52d17d59ee018609"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/KodastrDevelopment/hubbound-releases/releases/download/v#{version}/hubbound_linux_amd64.tar.gz"
      sha256 "8a7204240ef74bcb6737431de31a9755b009623cbed882b4d996686d2afd6673"
    end
    on_arm do
      url "https://github.com/KodastrDevelopment/hubbound-releases/releases/download/v#{version}/hubbound_linux_arm64.tar.gz"
      sha256 "13d36474554ac0c1087f520994700984492ec8e05c3377bfb4c58dfffaaa811c"
    end
  end

  service "run [opt_bin/"hubbound-agent", "run"]
keep_alive true
log_path var/"log/hubbound-agent.log"
error_log_path var/"log/hubbound-agent.err.log"
"

  # No zap stanza required
end
