# This file was generated by GoReleaser. DO NOT EDIT.
cask "hubbound" do
  name "hubbound"
  desc "Hubbound CLI, daemon, user agent, and privileged helper."
  homepage "https://hubbound.net"
  version "0.1.22-dev.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hubbound"
  binary "hubboundd"
  binary "hubbound-agent"
  binary "hubbound-helper"

  on_macos do
    on_intel do
      url "https://github.com/KodastrDevelopment/hubbound-releases/releases/download/v#{version}/hubbound_darwin_amd64.tar.gz"
      sha256 "fc401d062410c9096d25514d0a8d2e322051284320c3caf699623ae2346f6dbd"
    end
    on_arm do
      url "https://github.com/KodastrDevelopment/hubbound-releases/releases/download/v#{version}/hubbound_darwin_arm64.tar.gz"
      sha256 "dc242d4b1d2019d3b365fcb74d2f8999fe0e84dea39989e61929eda6c0bc309a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/KodastrDevelopment/hubbound-releases/releases/download/v#{version}/hubbound_linux_amd64.tar.gz"
      sha256 "47f726d0d1d981ea639e84e0e6b5644ef32a7d9f738097eac53a38f7215f4ea2"
    end
    on_arm do
      url "https://github.com/KodastrDevelopment/hubbound-releases/releases/download/v#{version}/hubbound_linux_arm64.tar.gz"
      sha256 "179269544f8caaf34f6b4d7c3fd21df75b31047f0702096f786ea136da784276"
    end
  end

  service "run [opt_bin/"hubbound-agent", "run"]
keep_alive true
log_path var/"log/hubbound-agent.log"
error_log_path var/"log/hubbound-agent.err.log"
"

  # No zap stanza required
end
