# This file was generated by GoReleaser. DO NOT EDIT.
cask "hubbound" do
  name "hubbound"
  desc "Hubbound CLI, daemon, user agent, and privileged helper."
  homepage "https://hubbound.net"
  version "0.1.29-dev.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hubbound"
  binary "hubboundd"
  binary "hubbound-agent"
  binary "hubbound-helper"

  on_macos do
    on_intel do
      url "https://github.com/KodastrDevelopment/hubbound-releases/releases/download/v#{version}/hubbound_darwin_amd64.tar.gz"
      sha256 "7a6ed113bb8aff5ec7dfb52881bbf58884c44c1c5bedcdc8f2ec78a2cd2aeabb"
    end
    on_arm do
      url "https://github.com/KodastrDevelopment/hubbound-releases/releases/download/v#{version}/hubbound_darwin_arm64.tar.gz"
      sha256 "658c1715df544231cd583a8c808cd686844c124c649f356b94f39c9da62c1a93"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/KodastrDevelopment/hubbound-releases/releases/download/v#{version}/hubbound_linux_amd64.tar.gz"
      sha256 "ef619840e8fc64aff8c3fee21f7e255f902a12a226c9f7499cf1b6320ca28833"
    end
    on_arm do
      url "https://github.com/KodastrDevelopment/hubbound-releases/releases/download/v#{version}/hubbound_linux_arm64.tar.gz"
      sha256 "be6916493b14a4da8dea44c8c9f2c6ceb7c1a2e6a9b3cb4321cc8c4cd233544e"
    end
  end

  service "run [opt_bin/"hubbound-agent", "run"]
keep_alive true
log_path var/"log/hubbound-agent.log"
error_log_path var/"log/hubbound-agent.err.log"
"

  # No zap stanza required
end
